package com.modusbox.bean;

public class SpreadsheetRecordBean {

	private String senderDfsp;
	private String senderPhoneName;
	private String senderAccountName;
	private String senderuserRoleType;
	private String senderAccountId;
	private String senderUUID;

	private String receiverDfsp;
	private String receiverPhoneName;
	private String receiverAccountName;
	private String receiverUserRoleType;
	private String receiverAccountId;
	private String receiverUUID;  
	
	
	
	public SpreadsheetRecordBean() {
		super();
	}
	
	public SpreadsheetRecordBean(String[] record) {
		super();
		this.setRecord(record);
	}
	

	public String getSenderPhoneName() {
		return senderPhoneName;
	}
	
	public void setSenderPhoneName(String senderPhoneName) {
		this.senderPhoneName = senderPhoneName;
	}
	
	public String getSenderAccountName() {
		return senderAccountName;
	}
	
	public void setSenderAccountName(String senderaccountName) {
		this.senderAccountName = senderaccountName;
	}
	
	public String getSenderUserRoleType() {
		return senderuserRoleType;
	}
	
	public void setSenderUserRoleType(String senderuserRoleType) {
		this.senderuserRoleType = senderuserRoleType;
	}
	
	public String getSenderAccountId() {
		return senderAccountId;
	}
	
	public void setSenderAccountId(String senderAccountId) {
		this.senderAccountId = senderAccountId;
	}
	
	public String getReceiverPhoneName() {
		return receiverPhoneName;
	}
	
	public void setReceiverPhoneName(String receiverPhoneName) {
		this.receiverPhoneName = receiverPhoneName;
	}
	
	public String getReceiverAccountName() {
		return receiverAccountName;
	}
	
	public void setReceiverAccountName(String receiverAccountName) {
		this.receiverAccountName = receiverAccountName;
	}
	
	public String getReceiverUserRoleType() {
		return receiverUserRoleType;
	}
	
	public void setReceiverUserRoleType(String receiverUserRoleType) {
		this.receiverUserRoleType = receiverUserRoleType;
	}
	
	public String getReceiverAccountId() {
		return receiverAccountId;
	}
	
	public void setReceiverAccountId(String receiverAccountId) {
		this.receiverAccountId = receiverAccountId;
	}
	
	
	public String[] getDataAsArray() {
		String[] data = new String[12];
		
		data[0] = this.getSenderDfsp();
		data[1] = this.getSenderPhoneName();
		data[2] = this.getSenderAccountName();
		data[3] = this.getSenderAccountId();
		data[4] = this.getSenderUserRoleType();
		data[5] = this.getSenderUUID();
		
		data[6] = this.getReceiverDfsp();
		data[7] = this.getReceiverPhoneName();
		data[8] = this.getReceiverAccountName();
		data[9] = this.getReceiverAccountId();
		data[10] = this.getReceiverUserRoleType();
		data[11] = this.getReceiverUUID();
		
		return data;
	}
	
	
	public static String[] getHeaderFieldsAsArray() {
		String[] data = new String[12];
		
		data[0] = "senderDFSP";  		//this.getSenderDfsp();
		data[1] = "senderName";  		//this.getSenderPhoneName();
		data[2] = "senderAccountName";  //this.getSenderAccountName();
		data[3] = "senderID";  	//this.getSenderAccountId();
		data[4] = "senderRoleType";  	//this.getSenderuserRoleType();
		data[5] = "senderUUID";			// Not generated by USSD, but here for convenience for some tests
		
		data[6] = "receiverDFSP";  		//this.getReceiverDfsp();
		data[7] = "receiverName";  		//this.getReceiverPhoneName();
		data[8] = "receiverAccountName";	//this.getReceiverAccountName();
		data[9] = "receiverID";  //this.getReceiverAccountId();
		data[10] = "receiverRoleType";	//this.getReceiverUserRoleType();
		data[11] = "receiverUUID";	// Not generated by USSD, but here for convenience for some tests
		
		return data;
	}

	public String getSenderDfsp() {
		return senderDfsp;
	}

	public void setSenderDfsp(String senderDfsp) {
		this.senderDfsp = senderDfsp;
	}

	public String getReceiverDfsp() {
		return receiverDfsp;
	}

	public void setReceiverDfsp(String receiverDfsp) {
		this.receiverDfsp = receiverDfsp;
	}
	
	
	/*
	 * Convenience method to set all the fields. 
	 */
	public void setRecord(String[] values) {
		this.senderDfsp = values[0];
		this.senderPhoneName = values[1];
		this.senderAccountName = values[2];
		this.senderAccountId = values[3];
		this.senderuserRoleType = values[4];
		this.senderUUID = values[5];
		
		this.receiverDfsp = values[6];
		this.receiverPhoneName = values[7];
		this.receiverAccountName = values[8];
		this.receiverAccountId = values[9];
		this.receiverUserRoleType = values[10];
		this.receiverUUID = values[11];
	}

	public String getSenderUUID() {
		return senderUUID;
	}

	public void setSenderUUID(String senderUUID) {
		this.senderUUID = senderUUID;
	}

	public String getReceiverUUID() {
		return receiverUUID;
	}

	public void setReceiverUUID(String receiverUUID) {
		this.receiverUUID = receiverUUID;
	}
}
